baseURL = 'https://unaisuarez.github.io/segundoHugoTarea/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'tale'


[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 2
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 3